---
title: "Projeto Insper Data - Politicas Publicas"
author: "Bruno, Bernardo e Vinicius"
date: "14/09/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---


Pacotes
```{r}

library(janitor)
library(vctrs)
library(tidyverse)
library(skimr)
library(readxl)
library(stringi)
library(rvest)
library(lubridate)
library(ggthemes)
library(spData)

```



Puxando as bases
```{r}

covid <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")


tests <- read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/testing/covid-testing-all-observations.csv")


CRT <- read_csv("https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv")


wjp_2019 <- read_excel("FINAL_2020_wjp_rule_of_law_index_HISTORICAL.xlsx", 
                        sheet = "WJP ROL Index 2019 Scores") 


democracy <- read_excel("EIU-Democracy Indices - Dataset - v3.xlsx", 
    sheet = "input-data-from-EIU-recentyrs", skip = 176)


giniOWID <- read_csv("economic-inequality-gini-index.csv")

```




Limpando as bases
```{r}

# Limpando a base de testes (Our World in Data)

t <- tests %>% 
  select("Entity":"ISO code", "Daily change in cumulative total":"Short-term positive rate") %>% 
  separate(Entity, c("country", "escala"), sep = " - ") %>% 
  rename(date = Date)
 
# Limpando a base Democracy Index (democracy)

skim(democracy)

colnames(democracy)[1] <- "location"

dmi <- democracy %>% 
        filter(!is.na(location)) %>% 
        mutate(`Electoral process and pluralism` = as.double(`Electoral process and pluralism`)) %>% 
        mutate(Rank = str_remove(Rank, "[=]$")) %>%
        mutate(location = str_remove(location, "of America")) %>% 
        mutate(Rank = as.integer(Rank)) %>% 
        mutate(type = case_when(
                      Rank <= 22 ~ "Full democracy",
                      Rank >= 23 & Rank <= 75 ~ "Flawed democracy",
                      Rank >= 77 & Rank <= 113 ~ "Hybrid regime",
                      Rank >= 114 ~ "Authoritarian regime"))
        
# Limpando a base World Justice Project (Instituições)

wjptidy <- wjp_2019 %>% 
  pivot_longer(-Country, names_to = "Countries", values_to = "Countries Codes") %>%
  pivot_wider(id_cols = c("Countries", "Countries Codes"), 
              names_from = "Country", values_from = "Countries Codes") %>% 
  select(-6) %>% 
  rename("iso_code" = "Country Code") %>% 
  rename("country_name" = "Countries")

wjptidy[, c(5:57)] <- sapply(wjptidy[, c(5:57)], as.numeric)

# Limpando Response Tracker


contador = round(as.numeric(difftime(Sys.Date(), "2020-09-13", units = "days"))) # gera um contador para restaura os EUA e UK
dias = (1: (257 + contador))

cpt <- CRT %>% 
  clean_names() %>% 
  mutate(date = ymd(date)) %>% 
  rename(c("iso_code" = "country_code")) %>% 
  select(- c(region_name, region_code)) %>% 
  relocate(confirmed_cases, .after = country_name)
  

us <- cpt %>% 
  filter(country_name == "United States") %>% 
  slice(dias)

uk <- cpt %>% 
  filter(country_name == "United Kingdom") %>% 
  slice(dias)


cpt <- cpt %>% 
  filter(country_name != "United States" & iso_code != "USA") %>% 
  filter(country_name != "United Kingdom" & iso_code != "GBR") %>%
  bind_rows(us) %>% 
  bind_rows(uk)

#Limpando Gini

giniOWIDlatest <- giniOWID %>% 
  group_by(Entity) %>% 
  filter(Year == max(Year)) %>% 
  rename(YearGINdata = Year) %>% 
  clean_names()


```



Juntando as bases
```{r}
# Unificação do World Justice com CPT

wjp_cpt <- left_join(cpt, wjptidy, by = ("iso_code")) %>% 
            select(-country_name.y) %>% 
            rename(country_name = country_name.x)

# Juntando Our world in data (covid) + Our world in data (t) +  Democracy Index (dmi)

junto <- covid %>% 
  left_join(dmi) %>%  
  left_join(t, by = c("location" = "country", "date" = "date")) %>% 
  select(-(new_tests:tests_units), -("ISO code")) %>% 
  filter(!is.na(type))


# Juntando tudo

base_semi <- left_join(wjp_cpt, junto,  by = c("country_name" = "location" , "date" = "date", "iso_code" =  "iso_code")) %>% 
  select(-Year)


#Juntando com Gini

base_inter <- left_join(base_semi, giniOWIDlatest, by = c("country_name" = "entity", "iso_code" = "code")) %>% 
  select(!(m1_wildcard))


```




Criando variável que conta quantos dias passaram desde que o país atingiu 1 caso por milhão de habitantes
```{r}

marcador <- base_inter %>%
  filter(total_cases_per_million >= 1) %>% 
  group_by(country_name) %>% 
  mutate(rank = min_rank(total_cases_per_million)) %>% 
  mutate(days_after_1pm = rank(rank, ties.method = "first")) %>% 
  relocate(days_after_1pm, .after = date) 

base <- left_join(base_inter, marcador) %>% 
  relocate(c(days_after_1pm, total_cases_per_million), .after = date)

rm(uk, us, base_semi, base_inter, marcador)


```


Análise descritiva - Democracy Index

```{r}
skim(dmi)

dmi %>%
  filter(`Overall Score` > 6) %>% 
  ggplot(aes(x = reorder(location, -`Overall Score`), `Overall Score`, fill = type)) + 
  geom_col() +
  coord_flip() +
  theme_clean()

dmi %>%
  filter(`Overall Score` < 6) %>% 
  ggplot(aes(x = reorder(location, -`Overall Score`), `Overall Score`, fill = type)) + 
  geom_col() +
  coord_flip() +
  theme_clean()

```


Análise descritiva - Oxford Covid-19 Government Response Tracker

```{r}
skim(cpt)

#Análise das variáveis "flag", que indicam se as políticas foram específicas ou gerais.

cpt %>% 
  select(country_name, c1_flag, 
         c2_flag, c3_flag, c4_flag, c5_flag,
         c6_flag, c7_flag, e1_flag, h1_flag) %>% 
  filter(!is.na(c1_flag), 
         !is.na(c2_flag), !is.na(c3_flag), 
         !is.na(c4_flag), !is.na(c5_flag),
         !is.na(c6_flag), !is.na(c7_flag), 
         !is.na(e1_flag), !is.na(h1_flag)) %>% 
  group_by(country_name) %>% 
  summarise(generalismo = mean((c1_flag + 
         c2_flag + c3_flag + c4_flag + c5_flag +
         c6_flag + c7_flag + e1_flag + h1_flag)/8)) 
  #Fazer mapa com isso, para ver o nível de generalismo das políticas ao redor do mundo

#Análise da variável C8 (International Travel Controls)

cpt %>% 
  select(country_name, c8_international_travel_controls, date) %>% 
  filter(!is.na(c8_international_travel_controls))
  #Fazer um gráfico, em mapa, dos travel controls ao longo do tempo

#Análise da relação entre C5 e E1

cpt %>% 
  select(country_name, c5_close_public_transport, e1_income_support) %>% 
  filter(!is.na(c5_close_public_transport), !is.na(e1_income_support)) %>% 
  group_by(country_name) %>% 
  summarise(media_fechamento_transporte = mean(c5_close_public_transport),
            media_suportederenda = mean(e1_income_support)) %>% 
  ggplot(mapping = aes(x = media_fechamento_transporte, y = media_suportederenda)) +
    geom_point() +
    geom_smooth(method = lm, se = FALSE)
  
#Análise da relação entre E4 e C8 
  
cpt %>% 
  select(country_name, e4_international_support, c8_international_travel_controls) %>% 
  filter(!is.na(e4_international_support), 
         !is.na(c8_international_travel_controls)) %>% 
  group_by(country_name) %>% 
  summarise(media_log_suporte = log(mean(e4_international_support)),
            media_controle = mean(c8_international_travel_controls)) %>% 
  filter(media_log_suporte > 0) %>% 
  ggplot(mapping = aes(x = media_log_suporte, y = media_controle)) +
    geom_point() +
    geom_smooth(se = FALSE)

#Análise H2 e H5



```










